name: Build Project

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_windows:
    name: "Build windows in Release"
    env:
      PARALLEL: -j 2
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: sccache
        uses: hendrikmuhs/ccache-action@v1.2.9
        with:
          key: ${{ github.job }}-${{ matrix.os }}
          variant: sccache
      - name: Configure and build
        shell: pwsh
        run: |
          cmake -B"build/windows" -G"Ninja" -DDOODLE_BUILD_EXAMPLES=OFF -DCMAKE_C_COMPILER_LAUNCHER=C:\\Users\\runneradmin\\.cargo\\bin\\sccache -DCMAKE_CXX_COMPILER_LAUNCHER=C:\\Users\\runneradmin\\.cargo\\bin\\sccache
          cmake --build "build/windows" --target doodle --config Release -j 1

  build_ubuntu:
    name: "Build ubuntu in Release"
    env:
      PARALLEL: -j 2
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install RandR headers
        run: |
          sudo apt-get update
          sudo apt install xorg-dev libglu1-mesa-dev
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.9
        with:
          key: ${{ github.job }}-${{ matrix.os }}
      - name: Configure and build
        run: |
          cmake -B"build/ubuntu" -DDOODLE_BUILD_EXAMPLES=OFF
          cmake --build "build/ubuntu" --target doodle --config Release ${{ env.PARALLEL }}
